USE TOOLSHOP;

CREATE TABLE SUPPLIER
	(SupplierID		INT		NOT NULL,
    Sname			VARCHAR(30)		NOT NULL,
    Stype			CHAR(1)			NOT NULL,
    Address			VARCHAR(30)		NOT NULL,
    CName			VARCHAR(15)		NOT NULL,
    Phone			CHAR(12)		NOT NULL,
    PRIMARY KEY (SupplierID));
CREATE TABLE TOOL
	(ToolID		INT				NOT NULL,
    Tname		VARCHAR(15)		NOT NULL,
    Ttype		CHAR(1) 	DEFAULT "R",
    Quantity	INT				NOT NULL	DEFAULT 0,
    Price		FLOAT 			NOT NULL,
    SupplierID	INT,
    PRIMARY KEY (ToolID),
    UNIQUE	(Tname),
    FOREIGN KEY( SupplierID) REFERENCES SUPPLIER(SupplierID));
CREATE TABLE ELECTRICAL
	(ToolID	INT	NOT NULL,
    PowerType	VARCHAR(10),
    PRIMARY KEY (ToolID),
    FOREIGN KEY	(ToolID) REFERENCES TOOL(ToolID));
CREATE TABLE INTERNATIONAL
	(SupplierID		INT		NOT NULL,
    ImportTax		FLOAT	DEFAULT 0,
    PRIMARY KEY (SupplierID),
    FOREIGN KEY (SupplierID) REFERENCES SUPPLIER(SupplierID));
CREATE TABLE ORDERS
	(OrderID		INT		NOT NULL,
    Odate			DATE	NOT NULL,
    PRIMARY KEY (OrderID));
CREATE TABLE ORDERLINE
	(OrderID		INT		NOT NULL,
    ToolID			INT		NOT NULL,
    SupplierID		INT		NOT NULL,
    Quantity		INT		NOT NULL,
    PRIMARY KEY (OrderID, ToolID),
    FOREIGN KEY(ToolID) REFERENCES TOOL(ToolID),
    FOREIGN KEY(SupplierID) REFERENCES SUPPLIER(SupplierID));
CREATE TABLE CLIENT
	(ClientID		INT		NOT NULL,
    Lname			VARCHAR(20)		NOT NULL,
    Fname			VARCHAR(20)		NOT NULL,
    Ctype			CHAR(1)			NOT NULL,
    Phone			VARCHAR(12)		NOT NULL,
    Address			VARCHAR(30)		NOT NULL,
    PostalCode		VARCHAR(7)		NOT NULL,
    PRIMARY KEY(ClientID));
CREATE TABLE PURCHASES
	(ClientID		INT		NOT NULL,
    ToolID			INT		NOT NULL,
    Pdate			DATE	NOT NULL,
    PRIMARY KEY(ClientID, ToolID, Pdate),
	FOREIGN KEY(ClientID) REFERENCES CLIENT(ClientID),
	FOREIGN KEY(ToolID) REFERENCES TOOL(ToolID));